rootProject.name = "TimeTracker"
include ':app'

// 启用JCenter仓库以支持MPAndroidChart库
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' } // 添加JitPack仓库支持MPAndroidChart
    }
}